-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.address_final DROP CONSTRAINT IF EXISTS fk1;

ALTER TABLE IF EXISTS public.address_final DROP CONSTRAINT IF EXISTS fk2;



DROP TABLE IF EXISTS public.county;

CREATE TABLE IF NOT EXISTS public.county
(
    county_id character varying(5) NOT NULL,
    "New County" character varying(20) NOT NULL,
    PRIMARY KEY (county_id)
);

DROP TABLE IF EXISTS public.city;

CREATE TABLE IF NOT EXISTS public.city
(
    city_id character varying(8) NOT NULL,
    business_city character varying(50) NOT NULL,
    PRIMARY KEY (city_id)
);

DROP TABLE IF EXISTS public.address_final;

CREATE TABLE IF NOT EXISTS public.address_final
(
    license_number character varying(15) NOT NULL,
    app_status character varying(12) NOT NULL,
    bus_name character varying(100),
    bus_phone character varying(14),
    bus_add character varying(100),
    city_id character varying(8),
    bus_state character varying(4),
    bus_zip character varying(8),
    new_lat character varying(20),
    new_long character varying(20),
    county_id character varying(5),
    PRIMARY KEY (license_number)
);

ALTER TABLE IF EXISTS public.address_final
    ADD CONSTRAINT fk1 FOREIGN KEY (city_id)
    REFERENCES public.city (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.address_final
    ADD CONSTRAINT fk2 FOREIGN KEY (county_id)
    REFERENCES public.county (county_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

select * from city

select * from county

select * from address_final